algoritmo "ConteAte10"
var
   contador : Inteiro
inicio
   contador <- 0
   Enquanto (contador <= 10) faca
      Escreval(contador)
      contador <- contador + 1
   FimEnquanto
   Escreval("Terminei de contar de 0 a 10")

   contador <- 10
   Enquanto (contador >= 0) faca
      Escreval(contador)
      contador <- contador - 1
   FimEnquanto
   Escreval("Terminei de contar de 10 a 0")
fimalgoritmo